aws:
  general:
    profile: default
    instances:
      instance_type: ''
      ssh_ingress_ip: ''
  networks:
    - region: 'us-east-1'
      stack_name: 'rp'
      instances:
        - stack_name: 'rp-use1-sn-1'
          keypair:
            aws_name: 'name-of-ec2-keypair'
            local_path: '/path/to/.ssh/name-of-ec2-keypair.pem'

azure:
  defaults:
    placeholder: 'todo'

bare_hosts:
  defaults:
    placeholder: 'todo'