AWSTemplateFormatVersion: '2010-09-09'

Metadata:
  Identifier: rocket-pool-node

Parameters:
  Ec2KeypairName:
    Type: String
    Description: The name of a keypair that you have created in the EC2 console.
  InstanceType:
    Type: String
    Description: The class of EC2 instance to create.
    Default: t3.medium
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the VPC subnet where the EC2 instance should be provisioned.
  UserIpAddress:
    Type: String
    Description: If you want to limit SSH to just your IP address, provide this value (strongly recommended). If your IP address changes, you will need to update the stack with your new IP address to resume SSH access.
    Default: ''
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the VPC where the EC2 instance and related resources should be provisioned.

Conditions:
  UserIpAddressProvidedCondition:
    !Not [!Equals [!Ref UserIpAddress, '']]

Mappings:
  # Ubuntu 18.04 LTS (EBS, HVM, SSD) AMI IDs
  # Retrieved 2020-05-02 from https://cloud-images.ubuntu.com/locator/ec2/
  AmiByRegion:
    ap-east-1:
      AmiId: ami-c790d6b6
    ap-northeast-1:
      AmiId: ami-0278fe6949f6b1a06
    ap-northeast-2:
      AmiId: ami-00edfb46b107f643c
    ap-northeast-3:
      AmiId: ami-00eac2261db3c9df5
    ap-south-1:
      AmiId: ami-0914f03407aa25fb8
    ap-southeast-1:
      AmiId: ami-0f7719e8b7ba25c61
    ap-southest-2:
      AmiId: ami-04fcc97b5f6edcd89
    ca-central-1:
      AmiId: ami-0edd51cc29813e254
    eu-central-1:
      AmiId: ami-0e342d72b12109f91
    eu-north-1:
      AmiId: ami-050981837962d44ac
    eu-west-1:
      AmiId: ami-0701e7be9b2a77600
    eu-west-2:
      AmiId: ami-0eb89db7593b5d434
    eu-west-3:
      AmiId: ami-08c757228751c5335
    me-south-1:
      AmiId: ami-051274f257aba97f9
    sa-east-1:
      AmiId: ami-077d5d3682940b34a
    us-east-1:
      AmiId: ami-085925f297f89fce1
    us-east-2:
      AmiId: ami-07c1207a9d40bc3bd
    us-west-1:
      AmiId: ami-0f56279347d2fa43e
    us-west-2:
      AmiId: ami-003634241a8fcdec0

Resources:
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: Role used for smart node instance profile.
      Path: /rocket-pool/
      Tags:
        - Key: Service
          Value: rocket-pool

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /rocket-pool/
      Roles:
        - !Ref InstanceRole

  KeystoreSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    Properties:
      Description: Keystore secret for Rocket Pool smart nodes in this region.
      GenerateSecretString:
        GenerateStringKey: KeystorePassword
        PasswordLength: 32
        RequireEachIncludedType: true
        SecretStringTemplate: '{}'
      Tags:
        - Key: Service
          Value: rocket-pool

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: rp-smartnode-eth
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic.
          FromPort: -1
          IpProtocol: -1
          ToPort: -1
      SecurityGroupIngress:
        - CidrIp: !If
            - UserIpAddressProvidedCondition
            - !Sub '${UserIpAddress}/32'
            - 0.0.0.0/0
          Description: Allow SSH to instance.
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          Description: Ethereum (IPv4, tcp)
          FromPort: 30303
          IpProtocol: tcp
          ToPort: 30303
        - CidrIp: 0.0.0.0/0
          Description: Ethereum (IPv4, udp)
          FromPort: 30303
          IpProtocol: udp
          ToPort: 30303
        - CidrIpv6: ::/0
          Description: Ethereum (IPv6, tcp)
          FromPort: 30303
          IpProtocol: tcp
          ToPort: 30303
        - CidrIpv6: ::/0
          Description: Ethereum (IPv6, udp)
          FromPort: 30303
          IpProtocol: udp
          ToPort: 30303
      Tags:
        - Key: Service
          Value: rocket-pool
      VpcId: !Ref VpcId

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      EbsOptimized: true
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !FindInMap
        - AmiByRegion
        - !Ref AWS::Region
        - AmiId
      InstanceInitiatedShutdownBehavior: stop
      InstanceType: !Ref InstanceType
      KeyName: !Ref Ec2KeypairName
      SecurityGroupIds:
        - !GetAtt InstanceSecurityGroup.GroupId
      SubnetId: !Ref SubnetId
      Tags:
        - Key: Service
          Value: rocket-pool

Outputs:
  InstanceId:
    Description: The ID of the EC2 instance created by this stack.
    Value: !Ref Instance
  InstanceIpAddress:
    Description: The Elastic IP address assigned to the EC2 instance created by this stack.
    Value: !GetAtt Instance.PublicIp
  InstanceUsername:
    Description: The username to use when opening an SSH session.
    Value: ubuntu