- name: get configuration
  include_vars: "{{ playbook_dir }}/config.yaml"

- name: deploy ec2 stack for each instance configuration
  loop: "{{ aws.networks | subelements('instances') | default([]) }}"
  register: aws_nodes
  cloudformation:
    profile: "{{ item.1.profile | default(aws.general.profile) }}"
    capabilities:
      - CAPABILITY_IAM
      - CAPABILITY_NAMED_IAM
      - CAPABILITY_AUTO_EXPAND
    on_create_failure: DELETE
    region: "{{ item.0.region }}"
    stack_name: "node-{{ item.1.stack_name }}"
    state: present
    template: "{{ role_path }}/files/ec2-instance.yaml"
    template_parameters:
      Ec2KeypairName: "{{ item.1.keypair.aws_name }}"
      InstanceType: "{{ item.1.instance_type | default(aws.general.instances.instance_type, true) | default(omit) }}"
      SubnetId: "{{ aws_network_stacks | json_query('results[?item.stack_name==`' ~ item.0.stack_name ~ '`] | [?item.region==`' ~ item.0.region ~ '`].stack_outputs.SubnetId | [0]') }}"
      UserIpAddress: "{{ item.1.ssh_ingress_ip | default(aws.general.instances.ssh_ingress_ip, true) | default(omit) }}"
      VpcId: "{{ aws_network_stacks | json_query('results[?item.stack_name==`' ~ item.0.stack_name ~ '`] | [?item.region==`' ~ item.0.region ~ '`].stack_outputs.VpcId | [0]') }}"

- name: add ec2 hosts to inventory
  loop: "{{ aws_nodes | json_query('results[*].{Outputs: stack_outputs, KeypairLocalPath: item[1].keypair.local_path}') }}"
  add_host:
    ansible_ssh_private_key_file: "{{ item.KeypairLocalPath}}"
    ansible_user: "{{ item.Outputs.InstanceUsername }}"
    groups:
    - aws
    hostname: "{{ item.Outputs.InstanceIpAddress }}"
    instance_id: "{{ item.Outputs.InstanceId }}"